name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Linux,   os: ubuntu-latest }
        - { name: Windows, os: windows-2025 }
        - { name: MacOS,   os: macos-latest }
    steps:
    - name: Set up SDL
      id: sdl
      uses: libsdl-org/setup-sdl@v1
      with:
        version: sdl3-latest
    - name: Set up Linux dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake libasound2-dev
    - name: Get SDL_native_midi sources
      uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B build ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/
